name: Build MindTheGapps

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 7 * *'

jobs:
  build:
    permissions:
      contents: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        arch: ["arm64"]
        androidv: ["15.0.0"]
    name: Build ${{ matrix.androidv }}-${{ matrix.arch }}
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Map version to tree
        run: |
          declare -A ANDROID_VER_MAP=(["12.1.0"]="sigma" ["13.0.0"]="tau" ["14.0.0"]="upsilon" ["15.0.0"]="vic")
          echo "ANDROIDV=${ANDROID_VER_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV
          declare -A ANDROID_API_MAP=(["12.1.0"]=32 ["13.0.0"]=33 ["14.0.0"]=34 ["15.0.0"]=35)
          echo "ANDROID_API=${ANDROID_API_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV

      - name: Clone repository
        run: |
          git config --global http.version HTTP/1.1
          git clone --depth=1 -b ${{ env.ANDROIDV }} https://gitlab.com/MindTheGapps/vendor_gapps.git/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Replace build script
        run: cp -f build.sh vendor_gapps/build/gapps.sh

      - name: Build
        working-directory: vendor_gapps
        run: |
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          ./build/gapps.sh ${{ matrix.androidv }} ${{ env.ANDROID_API}} ${{ matrix.arch }}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: vendor_gapps/out/*.*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.date }}
          draft: false
          prerelease: false
          files: vendor_gapps/out/${{ matrix.arch }}/${{ env.date }}/*.*
